# Generated by Django 3.1.5 on 2021-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_statement',
            field=models.TextField(default=''),
        ),
    ]
